server:
  port: 0
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/job_finder_headHunter_service_db
    username: root
    password: root
  application:
    name: headHunter-ms
jpa:
  show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka
jwt:
  secret: apple