server:
  port: 5555
spring:
  application:
    name: gateway-server
  cloud:
    discovery:
      enabled: true;
    gateway:
      gdefault-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credetials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      metrics:
        enabled: true
      disovery:
        locator:
          enabled: true
          lower-case-servie-id: true
      routes:
        - id: user-ms
          uri: lb://user-ms
          predicates:
            - Path=/auth/**

        - id: headHunter-ms
          uri: lb://headHunter-ms
          predicates:
            - Path=/hh_service/**

    loadbalaner:
      ribbon:
        enabled: false
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}